<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,0,'5Zyo57q/55WZ6KiA');
$cfg_Cs[2]=array(0,1,0,'5bCP6K+0');
$cfg_Cs[3]=array(0,1,0,'6buE6aG1');
$cfg_Cs[4]=array(0,1,0,'6Zeu562U');
$cfg_Cs[5]=array(0,1,0,'5ZyI5a2Q');
$cfg_Cs[8]=array(0,1,0,'cGxheQ==');
$cfg_Cs[9]=array(8,1,1,'cGxheUE=');
$cfg_Cs[10]=array(8,1,1,'cGxheUI=');
$cfg_Cs[11]=array(8,1,1,'cGxheUM=');
$cfg_Cs[12]=array(0,1,1,'c2luZw==');
$cfg_Cs[13]=array(12,1,1,'c2luZ0E=');
$cfg_Cs[14]=array(12,1,1,'c2luZ0I=');
?>