SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`mianimg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mianimg` (
  `mid` INT NULL AUTO_INCREMENT COMMENT '主键',
  `tuan` CHAR(225) NOT NULL DEFAULT '' COMMENT '精品团购',
  `tese` CHAR(225) NOT NULL DEFAULT '' COMMENT '特色购',
  `lun` CHAR(225) NOT NULL DEFAULT '' COMMENT '一楼轮播图',
  `luna` CHAR(225) NOT NULL DEFAULT '' COMMENT '二楼轮播',
  `lunb` CHAR(225) NOT NULL DEFAULT '' COMMENT '三楼楼轮播',
  `lunc` CHAR(225) NOT NULL DEFAULT '' COMMENT '四楼轮播',
  `first` CHAR(225) NOT NULL DEFAULT '' COMMENT '楼层首图',
  PRIMARY KEY (`mid`))
ENGINE = MyISAM
COMMENT = '首页图片数据表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
